# Form implementation generated from reading ui file 'gui/blackjack.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(850, 800)
        MainWindow.setMinimumSize(QtCore.QSize(850, 800))
        MainWindow.setMaximumSize(QtCore.QSize(850, 800))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedwidget_content = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedwidget_content.sizePolicy().hasHeightForWidth())
        self.stackedwidget_content.setSizePolicy(sizePolicy)
        self.stackedwidget_content.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedwidget_content.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedwidget_content.setStyleSheet("#page_1_menu  {\n"
"background-color:rgba(59,82,63,255);\n"
"}\n"
"\n"
"#page_2_game {\n"
"background-color: rgba(52,14,16,255);\n"
"background-color: rgb(60,27,12);\n"
"background-color: rgb(68,11,20);\n"
"}\n"
"\n"
"")
        self.stackedwidget_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stackedwidget_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stackedwidget_content.setObjectName("stackedwidget_content")
        self.page_1_menu = QtWidgets.QWidget()
        self.page_1_menu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.page_1_menu.setStyleSheet("\n"
"\n"
"QPushButton::hover {\n"
"border: 2px solid rgba(212,185,58,255);\n"
"background-color: rgba(212,185,58,25);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 16pt \"Arial\";\n"
"border: 2px solid  rgb(120,124,116);\n"
"border-radius: 25px;\n"
"color: rgba(212,185,58,255);\n"
"background-color: rgba(39,52,45,255);\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox {\n"
"color: rgba(212,185,58,255);\n"
"background-color: transparent;\n"
"font: 700 16pt \"Arial\";\n"
"border:  2px solid rgb(45, 20, 9);\n"
"border-radius: 25px;\n"
"margin: 10px 0 0 0;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-position: top center; /* Başlığı ortalamak için */\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}")
        self.page_1_menu.setObjectName("page_1_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1_menu)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(10, 20, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
